title: My Awesome Home
views:
  - path: default_view
    title: Home
    visible:
      - user: d427a22cbc294d8fbf79d957ac98761c
      - user: aa407a5348d94966aefb6044664c7cbb
    badges:
      - binary_sensor.updater
      - binary_sensor.remote_ui
      - entity: input_boolean.damon_hk_present
        name: Damon at home
      - person.damon_vincent
      - sun.sun
    cards:
      - entity: weather.home
        type: weather-forecast
      - type: entities
        title: Outdoor Conditions
        entities:
          - entity: sensor.acurite_5n1_temperature
            name: Temperature
          - entity: sensor.acurite_5n1_humidity
            icon: mdi:water-percent
            name: Humidity
          - entity: sensor.rainfall_24_hours
            type: custom:multiple-entity-row
            icon: mdi:weather-rainy
            name: Rainfall 24h
            secondary_info: 
              entity: sensor.acurite_5n1_message_age
              name: age
            entities:
              - entity: sensor.rainfall_last_hour
                name: 1h
              - entity: sensor.rainfall_last_7_days
                name: 7d
              - entity: sensor.rainfall_last_30_days
                name: 30d
          - entity: sensor.acurite_5n1_wind_speed
            type: custom:multiple-entity-row
            name: Wind
            unit: mph
            icon: mdi:weather-windy
            entities:
              - entity: sensor.acurite_5n1_wind_direction
                name: false
      - title: Living Room
        type: entities
        show_header_toggle: true
        entities:
          - light.foyer_lamp
          - light.living_room_lamp
      - title: Devices
        type: entities
        show_header_toggle: true
        entities:
          - entity: switch.3dprinter
            name: 3D Printer Power
          - entity: switch.octopi
            name: Octopi Power
      - title: Outside House
        show_header_toggle: true
        type: entities
        entities:
          - entity: switch.garage_outside_lights
          - entity: switch.front_porch_lights
          - entity: input_datetime.nightlights_offtime
      - type: custom:mini-graph-card
        entities:
         - entity: sensor.acurite_5n1_wind_speed
           unit: 'mph'
      # - entities:
      #   - switch.north_garage_door_switch
      #   - switch.center_garage_door_switch
      #   - switch.south_garage_door_switch
      #   - switch.restart_garage_door_device
      #   show_header_toggle: true
      #   title: Outside House
      #   type: entities
      # - type: light
      #   entity: light.treadmill_speed
  - title: Shop
    visible:
      - user: d427a22cbc294d8fbf79d957ac98761c
      - user: aa407a5348d94966aefb6044664c7cbb
    cards:
      - type: entities
        title: Fans
        entities:
          - entity: fan.exhaust
            name: Exhaust fan
          - entity: light.bayceilingfan
            name: Bay Ceiling fans
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
        - entity: switch.baylights
          name: Bay lights
        - entity: switch.shedstorageroomlight
          name: Storage room lights
        - entity: switch.leantolights
          name: Lean to lights
      - type: entities
        title: Doors
        show_header_toggle: false
        entities:
        - entity: cover.southwest_overhead_door
          name: Southwest Door
        - entity: cover.southcenter_overhead_door
          name: Center Door
        - entity: cover.southeast_overhead_door
          name: Southeast Door
        - entity: cover.northeast_overhead_door
          name: Northeast Door
      - type: entities
        title: Presence
        show_header_toggle: false
        entities:
        - entity: input_boolean.shop_occupied
          name: Shop occupied
        - entity: timer.motion_timeout
          name: Motion Timer
        - entity: timer.shutdown_timer
          name: Shutdown Timer
        - entity: sensor.shop_occupied_12hrs
          name: Occupied Triggers 12hrs
      - type: thermostat
        entity: climate.shop_east_thermostat
      - type: thermostat
        entity: climate.shop_west_heat
      - type: 'custom:simple-thermostat'
        entity: climate.shop_heat
        step_layout: row
        name: true
        icon: false
        control: false
  - title: Greenhouse
    badges:
      - entity: sensor.greenhouse_inside_temperature
        name: Sensor Temp
      - entity: sensor.greenhouse_voltage
        name: Voltage
      - entity: sensor.solarpaneltilt
        name: Tilt
      - entity: sensor.sun_azimuth
        name: Azimuth
      - entity: sensor.sun_elevation
        name: Elevation
    cards:
        - type: custom:mini-graph-card
          name: Temperatures
          entities:
          - entity: sensor.greenhouse_inside_temperature
            name: Inside Temperature
          - entity: sensor.greenhouse_soil_temperature
            name: Bed Temp
          - entity: sensor.greenhouse_outside_temperature
            name: Outside Temp
        - type: entities
          title: Controls
          show_header_toggle: false
          entities:
            - entity: switch.greenhouse_irrigation
              name: Irrigation
            - entity: switch.greenhouse_light
              name: Lights
            - entity: switch.6301574084f3ebed1dff_4
              name: Battery Charger
            - entity: sensor.uptime
              name: ESP32 Uptime
        - type: 'custom:simple-thermostat'
          entity: climate.greenhouse_main_thermostat
          name: Main
          step_layout: row
          icon: false
          control: false
        - type: 'custom:simple-thermostat'
          entity: climate.greenhouse_bed_thermostat
          step_layout: row
          name: Heated Bed
          icon: false
          control: false
        - type: 'custom:simple-thermostat'
          entity: climate.greenhouse_vent_thermostat
          step_layout: row
          name: Vent
          icon: false
          control: false
        - type: 'custom:simple-thermostat'
          entity: climate.greenhouse_earth_battery_thermostat
          step_layout: row
          name: Earth Battery
          icon: false
          control: false
        - type: entities
          title: Temperature Control
          show_header_toggle: false
          entities:
            - entity: switch.greenhouse_vent
              name: Vent
            - entity: fan.battery_fan_forward
              name: Fan forward
            - entity: fan.battery_fan_reverse
              name: Fan reverse
            - entity: switch.6301574084f3ebed1dff_1
              name: West Heater
            - entity: switch.6301574084f3ebed1dff_2
              name: East Heater
            - entity: switch.6301574084f3ebed1dff_3
              name: Bed Heater
        - type: entities
          title: Solar
          show_header_toggle: false
          entities:
            - entity: sensor.solarpaneltilt
              name: Tilt
            - entity: sensor.sun_azimuth
              name: Azimuth
            - entity: sensor.sun_elevation
              name: Elevation
            - entity: cover.solarpanel
              name: Solar panel
        - type: custom:mini-graph-card
          name: Power
          entities:
          - entity: sensor.greenhouse_voltage
            unit: 'Volts'
            name: Voltage
          - entity: sensor.greenhouse_current
            name: Current
            unit: 'Amps'
          - entity: sensor.greenhouse_power
            name: Power
            unit: 'Watt'
  # - title: Cameras
  #   cards:
  #     - camera_view: live
  #       entity: camera.garage
  #       type: picture-entity
  #     - camera_view: live
  #       entity: camera.kitchen
  #       type: picture-entity
  #     - camera_view: live
  #       entity: camera.furnace
  #       type: picture-entity
  #     - camera_view: live
  #       entity: camera.basement
  #       type: picture-entity
  - title: Iphone Tracker
    visible:
      - user: d427a22cbc294d8fbf79d957ac98761c
      - user: aa407a5348d94966aefb6044664c7cbb
    cards:
    - type: "custom:icloud3-event-log-card"
      entity: sensor.icloud3_event_log
