esphome:
  name: esp32_garage
  platform: ESP32
  board: lolin_d32_pro

wifi:
  ssid: !secret wifi
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Garage Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api

ota:
  password: !secret esp_api
  
switch:
  - platform: gpio
    name: "South Garage Door"
    pin: 5

esp32_ble_tracker:
  scan_parameters:
    active: true