esphome:
  name: esp_mill
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi
  password: !secret wifi_password
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Mill Fallback Hotspot"
    password: !secret wifi_password
  manual_ip:
    static_ip: !secret esp_mill_ip
    gateway: !secret router_ip
    subnet: 255.255.255.0
    dns1: !secret router_ip
    
captive_portal:

debug:

# Enable logging
logger:
  level: debug
  
# Enable Home Assistant API
api:
  password: !secret esp_api

ota:
  password: !secret esp_api
  
i2c:
  sda: 21
  scl: 22
  scan: True

sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "INA219 Current"
    power:
      name: "INA219 Power"
    bus_voltage:
      name: "INA219 Bus Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 5s